/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_columbia_cs_psl_phosphor_runtime_ProfileCount */

#ifndef _Included_edu_columbia_cs_psl_phosphor_runtime_ProfileCount
#define _Included_edu_columbia_cs_psl_phosphor_runtime_ProfileCount
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_columbia_cs_psl_phosphor_runtime_ProfileCount
 * Method:    printStatus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_columbia_cs_psl_phosphor_runtime_ProfileCount_printStatus
  (JNIEnv *, jclass);

/*
 * Class:     edu_columbia_cs_psl_phosphor_runtime_ProfileCount
 * Method:    invoke
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_columbia_cs_psl_phosphor_runtime_ProfileCount_invoke
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
